version: '3.3'

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
        
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: booking_api
      MYSQL_ROOT_PASSWORD: root
      
    volumes:
      - my-db:/var/lib/
      - ./mysql-files:/var/lib/mysql-files
    networks:
      app_net:
        ipv4_address: 172.16.238.10

  admin_microservice:
    container_name: admin_microservice
    build: admin_microservice/
    depends_on:
      - db
    networks:
      app_net:
        ipv4_address: 172.16.238.12
    ports:
        - 7070:10000

  grpc_server:
    container_name: grpc_server
    build: grpc_server/
    depends_on:
      - db
    networks:
      app_net:
        ipv4_address: 172.16.238.11
    ports:
        - 50051:50051 
  
  login_microservice:
    container_name: login_microservice
    build: login_microservice/
    depends_on:
      - db
      - grpc_server
    networks:
      app_net:
        ipv4_address: 172.16.238.13
    ports:
        - 7071:10001  
# Names our volume
volumes:
  my-db:
