version: '3.3'

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
        
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: booking_api
      MYSQL_ROOT_PASSWORD: root
      
    volumes:
      - my-db:/var/lib/
      - ./mysql-files:/var/lib/mysql-files
    networks:
      app_net:
        ipv4_address: 172.16.238.10
      
  booking-server:
    container_name: booking-server
    build: .
    depends_on:
      - db
    networks:
      app_net:
        ipv4_address: 172.16.238.11
    ports:
        - 7070:10000        
  
# Names our volume
volumes:
  my-db:
